services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend:cached
      - node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true
    environment:
      - HOST=0.0.0.0
      # - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn dev"
  blockchain:
    platform: linux/x86-64
    build:
      context: .
      dockerfile: blockchain/Dockerfile
    volumes:
      - ./blockchain:/usr/src/app
    ports:
      - "7878:7878"
    tty: true

volumes:
  node_modules:
