services:
  blockchain:
    platform: linux/x86-64
    build:
      context: .
      dockerfile: blockchain/Dockerfile
    volumes:
      - ./blockchain:/usr/src/app
    ports:
      - "7878:7878"
    tty: true

